export const database_Dummy = {
	dummy_users: [
		{
			id: "alu1",
			tipo: "estudiante",
			nombre: "Roberto",
			apellido: "Salinas",
			password: "12345678",
			mail: "testalu1@test.com",
			celular: "1234",
			fechaNacimiento: "2015-03-25",
			estudiosCursados: ["primario", "secundario", "universidad"],
			cursos: [
				{ curso: "curso1", estado: "aceptado" },
				{ curso: "curso2", estado: "aceptado" },
				{ curso: "curso4", estado: "finalizado" },
			],
		},

		{
			id: "profesor1",
			tipo: "profesor",
			nombre: "Maria",
			apellido: "Maria",
			password: "12345678",
			mail: "testprof1@test.com",
			celular: "1234",
			titulo: "licenciado",
			experiencia: "trabaje en microsoft",
			cursos: ["curso1", "curso3", "curso4"],
		},
		{
			id: "profesor2",
			tipo: "profesor",
			nombre: "Jose",
			apellido: "Aguilar",
			password: "12345678",
			mail: "testprof2@test.com",
			celular: "1234",
			titulo: "Ingeniero",
			experiencia: "trabaje en Uber",
			cursos: ["curso2"],
		},
	],
	cursos_dummy: [
		{
			idCurso: "curso1",
			estado: true, //indica si esta en estado publicado (true) o si esta despublicado (false)
			nombreCurso: "Mate101",
			image: "https://www.apwa.net/images/PWM101.jpg",
			profesor: "profesor1",
			desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ipsa, facilis quidem aliquam molestiae earum magnam impedit, laboriosam odio fuga corporis cupiditate! Quam repudiandae neque, debitis voluptates repellendus libero molestias?",
			alumnos: ["alu1"], //tener a los alumnos aqui me sirve
			duracion: "1 mes",
			frecuencia: "mensual",
			tipo: "grupal",
			costo: 12.99,
			calificacion: 1, //cada vez que un usuario califique se armara un request que venga y recalcule este valor
		},
		{
			idCurso: "curso2",
			estado: true,
			nombreCurso: "Biology101",
			image: "https://www.apwa.net/images/PWM101.jpg",
			profesor: "profesor2",
			desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ipsa, facilis quidem aliquam molestiae earum magnam impedit, laboriosam odio fuga corporis cupiditate! Quam repudiandae neque, debitis voluptates repellendus libero molestias?",
			alumnos: ["alu1"],
			duracion: "2 meses",
			frecuencia: "mensual",
			tipo: "individual",
			costo: 14.99,
			calificacion: 2,
		},
		{
			idCurso: "curso3",
			estado: true,
			nombreCurso: "API101",
			image: "https://www.apwa.net/images/PWM101.jpg",
			profesor: "profesor1",
			desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ipsa, facilis quidem aliquam molestiae earum magnam impedit, laboriosam odio fuga corporis cupiditate! Quam repudiandae neque, debitis voluptates repellendus libero molestias?",
			alumnos: [],
			duracion: "5 dias",
			frecuencia: "semanal",
			tipo: "individual",
			costo: 2.99,
			calificacion: 4,
		},
		{
			idCurso: "curso4",
			estado: true,
			nombreCurso: "Statistics101",
			image: "https://www.apwa.net/images/PWM101.jpg",
			profesor: "profesor1",
			desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus ipsa, facilis quidem aliquam molestiae earum magnam impedit, laboriosam odio fuga corporis cupiditate! Quam repudiandae neque, debitis voluptates repellendus libero molestias?",
			alumnos: ["alu1"],
			duracion: "3 meses",
			frecuencia: "semanal",
			tipo: "individual",
			costo: 12.99,
			calificacion: 5,
		},
	],
	calificaciones_dummy: [
		{
			id: "rating1",
			alumno: "alu1",
			curso: "curso2",
			valor: 5,
		},
		{
			id: "rating2",
			alumno: "alu1",
			curso: "curso4",
			valor: 4,
		},
	],
	comentarios_dummy: [
		{
			id: "comentario1",
			alumno: "alu1",
			curso: "curso1",
			contenido: "Curso muy malo",
			estado: false,
		},
		{
			id: "comentario2",
			alumno: "alu1",
			curso: "curso2",
			contenido: "Curso muy bueno",
			estado: true,
		},
		{
			id: "comentario3",
			alumno: "alu1",
			curso: "curso4",
			contenido: "Curso promedio y aburrido",
			estado: false,
		},
	],
	notificaciones_dummy: [
		{
			id: `notificacion1`,
			mensaje: "Borrado por mensaje ofensivo",
			alumno: `alu1`,
			curso: `curso1`,
			contenidoComentario: `El curso no sirve para nada`,
		},
	],
	contrataciones_dummy: [
		{
			id: `contratacion1`,
			motivacion: "Me gusta la programacion",
			alumno: `alu1`,
			curso: `curso3`,
			mail: "testalu1@email.com",
			telefono: "541166784884",
			horario: "10AM-10PM Lunes",
		},
	],
};
